cors:
  allow_origins:
    - "http://localhost:5174"

db:
  postgres:
    host: "localhost"
    port: 54322
    user: "postgres"
    password: ${ENV_DB_PASSWORD}
    database: "sauron_db"

llm:
  provider: "gemini"
  model: "gemini-2.5-flash"
  temperature: 0.3

source_control:
  ENCRYPTION_KEY: ${SCM_AUTH_ENCRYPTION_KEY}

log:
  opensearch:
    host: "localhost"
    port: 9200
